spring:
  datasource:
    url: jdbc/mysql:localhost:3306/drugs
    name: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080